apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ include "otelCollector.fullname" . }}
  name: {{ .Values.clusterRole.name }}
rules:
- apiGroups:
  - ""
  resources:
  {{- toYaml .Values.clusterRole.rules.all.resources | nindent 2 }}
  verbs:
  {{- toYaml .Values.clusterRole.rules.all.verbs | nindent 2 }}
- apiGroups:
  - networking.k8s.io
  resources:
  {{- toYaml .Values.clusterRole.rules.networking.resources | nindent 2 }}
  verbs:
  {{- toYaml .Values.clusterRole.rules.networking.verbs | nindent 2 }}
- nonResourceURLs:
  {{- toYaml .Values.clusterRole.rules.nonResourceURLs | nindent 2 }}
  verbs:
  {{- toYaml .Values.clusterRole.rules.nonResourceURLVerbs | nindent 2}}