---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: otel
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
      prometheus_simple:
        endpoint: "prometheus.istio-system:9090"
        collection_interval: 10s
        metrics_path: /federate
        params:
            match[]:
            - 'istio_requests_total'
            - 'istio_request_duration_milliseconds_bucket'
            - 'istio_request_bytes_count'
            - 'istio_request_bytes_sum'
            - 'istio_response_bytes_count'
            - 'istio_response_bytes_sum'
            - 'istio_request_messages_total'
            - 'istio_response_messages_total'
            - 'istio_tcp_sent_bytes_total'
            - 'istio_tcp_received_bytes_total'
            - 'istio_tcp_connections_opened_total'
            - 'istio_tcp_connections_closed_total'
      prometheus:
        config:
          scrape_configs:
            - job_name: 'istiod'
              kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                  - istio-system
              relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring
            - job_name: 'envoy-stats'
              metrics_path: /stats/prometheus
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
    processors:
    exporters:
      logging:
        loglevel: info
      prometheusremotewrite:
        endpoint: "https://metrics.cloud.aspenmesh.io/write"
        external_labels:
          cluster: aspenmesh-saas-demo-otel
          __replica__: otel-replica
        timeout: 30s
        headers:
          TENANT: {{ .Values.otelcollector.tenantName }}
          Authorization: Basic cHJvbXNjYWxlOlFuVXlOMVZaV2paVGNWSldMMmhrZUc1aU1qRjJjbFIyY0dZeldUWXJNRWd5WXpOVGRUQXZiMUZGU1QwSw==
    service:
      pipelines:
        metrics:
          receivers: [otlp,prometheus_simple]
          processors: []
          exporters: [logging,prometheusremotewrite]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: otel
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      logging:
      otlp:
        endpoint: "opentelemetrycollector.otel.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp,logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlp,logging]