apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: am-collector-role
  labels:
    app: {{ include "aspenmeshCollector.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
    - configmaps
    - endpoints
    - namespaces
    - namespaces/status
    - nodes
    - nodes/spec
    - nodes/stats
    - nodes/proxy
    - nodes/metrics
    - pods
    - pods/status
    - replicationcontrollers
    - replicationcontrollers/status
    - resourcequotas
    - services
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - apps
  resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - autoscaling
  resources:
    - horizontalpodautoscaler
  verbs:
    - list
    - watch
- apiGroups:
  - extensions
  resources:
    - daemonsets
    - deployments
    - replicasets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
    - get