---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: 
      prometheus:
        config:
          scrape_configs:
            - job_name: kube-state-metrics
              static_configs:
              - targets:
                - aspenmesh-collector-kube-state-metrics.{{ .Release.Namespace }}.svc.cluster.local:8080
            - job_name: 'envoy-stats'
              metrics_path: /stats/prometheus
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
    processors:
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
      resourcedetection/eks:
        detectors: [env, eks]
        timeout: 2s
        override: false
      resourcedetection/aks:
        detectors: [env, aks]
        timeout: 2s
        override: false
      resourcedetection/gke:
        detectors: [env, gke]
        timeout: 2s
        override: false
    exporters:
      logging:
        loglevel: info
      prometheusremotewrite:
        endpoint: {{ .Values.endpoint | default "https://metrics.cloud.aspenmesh.io/write" | quote }}
        timeout: 30s
        headers:
          X-AM-API-KEY: {{ required "An API key is required." .Values.apiKey | quote }}
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        metrics:
          receivers: 
            - otlp
            - prometheus
          processors:
            - k8sattributes
            - resourcedetection/eks
            - resourcedetection/aks
            - resourcedetection/gke
          exporters: 
            - logging
            - prometheusremotewrite
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    kubeletstats:
      collection_interval: 60s
      auth_type: "serviceAccount"
      endpoint: "${K8S_NODE_NAME}:10250"
      insecure_skip_verify: true
      metric_groups:
      - containers
      - pod
    processors:
    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: aspenmesh-collector.{{ .Release.Namespace }}.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: []
          exporters: 
