apiVersion: v2
name: aspenmesh-collector
type: application
version: 0.1.7
appVersion: 0.1.0
description: Aspen OpenTelemetry Collector
icon: https://aspenmesh.github.io/aspenmesh-charts/docs/images/aspenmesh.png
dependencies:
  - name: cert-manager
    condition: cert-manager.enabled
    version: 1.10.1
    repository: "https://charts.jetstack.io"
  - name: kube-state-metrics
    version: 4.24.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: custom-pod-autoscaler-operator
    version: 1.3.0
    repository: ""
