apiKey:
cert-manager:
  enabled: true
  installCRDs: true
kube-state-metrics:
  collectors:
    - replicasets
    - horizontalpodautoscalers
    - deployments
    - pods
    - services
  metricLabelsAllowlist:
    - replicasets=[app.kubernetes.io/name,app.kubernetes.io/version,app,version]
    - horizontalpodautoscalers=[app.kubernetes.io/name,app.kubernetes.io/version,app,version]
    - deployments=[app.kubernetes.io/name,app.kubernetes.io/version,app,version]
    - pods=[app.kubernetes.io/name,app.kubernetes.io/version,app,version]
    - services=[app.kubernetes.io/name,app.kubernetes.io/version,app,version]
  