apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "frontend.fullname" . }}-gateway
  namespace: {{ .Values.namespace}}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- toYaml .Values.hostnames | nindent 8 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  namespace: {{ .Values.namespace}}
spec:
  hosts:
  {{- toYaml .Values.hostnames | nindent 4 }}
  gateways:
  - {{ include "frontend.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "frontend.fullname" . }}
        port:
          number: {{ .Values.service.port }}
