---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "aspenmeshAgent.fullname" . }}
  labels:
    {{- include "aspenmeshAgent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aspenmeshAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aspenmeshAgent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: am-collector-sa
      containers:
        - name: am-agent
          image: "ghcr.io/aspenmesh/aspenmesh-collector:0.1.1"
          args:
            - "--config=/conf/agent.yaml"
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - name: agent-config
              mountPath: /conf
          ports:
          - containerPort: 4317
          - containerPort: 8888
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
            items:
              - key: agent.yaml
                path: agent.yaml
