version: 2.1

jobs:
  release:
    docker:
      - image: ghcr.io/banzaicloud/helm:0.0.8
    steps:
      - checkout
      - run:
          name: Helm package
          command: |
            TAG=0.1.0
            helm package aspenmesh-demo/ --version $TAG            
      - run:
          name: Helm package
          command: |
            TAG=0.1.0
            helm package otel/ --version $TAG            
      - run:
          name: Helm index
          command: |
            helm repo index --url https://aspenmesh.github.io/aspenmesh-demo-site-charts/ --merge index.yaml .
      - add_ssh_keys:
          fingerprints:
            - "3c:79:68:98:84:35:59:e0:5a:f9:2b:be:c1:b1:7f:da"
      - run:
          name: Commit changes
          command: |
            git config user.email "bjimerson@gmail.com"
            git config user.name "CircleCI Job"
            git add .
            git commit --allow-empty -am "Packaged helm chart version 0.1.0 [skip ci]"
            git push origin main

workflows:
  helm-chart-release:
    jobs:
      - release
      
