apiVersion: v2
name: aspenmesh-collector
type: application
version: 1.0.0
appVersion: "0.1.0"
description: Aspen Mesh Collector
icon: https://https://aspenmesh.github.io/aspenmesh-charts/docs/images/aspenmesh.png

