cert-manager:
  installCRDs: true
serviceAccount: 
  name: am-collector-sa
clusterRole:
  name: am-collector-role
  rules:
    all:
      resources:
        - nodes
        - nodes/metrics
        - services
        - endpoints
        - pods
        - configmaps
      verbs:
        - get
        - list
        - watch
    networking:
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch
    nonResourceURLs:
    - /metrics
    - /metrics/cadvisor
    nonResourceURLVerbs:
        - get
clusterRoleBinding:
  name: am-collector-role-binding
aspenmeshCollector:
  replicaCount: 1
  image:
    repository: ghcr.io/aspenmesh/aspenmesh-collector 
    pullPolicy: Always
    tag: "0.1.1"
  nameOverride: "amcollector"
  fullnameOverride: "amcollector"
  containerPort: 4317
  container:
    name: "am-collector"
    args:
    - --config=/conf/collector.yaml
    volumeMounts:
    - mountPath: /conf
      name: collector-config
  volumes:
  - name: collector-config
    configMap:
      name: collector-config
      items:
      - key: collector.yaml
        path: collector.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
  collectorConfig:
    name: "collector-config"
    enableOtlpReceiver: true
    otlpReceiver:
      protocols:
        grpc:
    enablePrometheusSimpleReceiver: true
    prometheusSimpleReceiver:
      matchParams:
      - 'istio_requests_total'
      - 'istio_request_duration_milliseconds_bucket'
      - 'istio_request_bytes_count'
      - 'istio_request_bytes_sum'
      - 'istio_response_bytes_count'
      - 'istio_response_bytes_sum'
      - 'istio_request_messages_total'
      - 'istio_response_messages_total'
      - 'istio_tcp_sent_bytes_total'
      - 'istio_tcp_received_bytes_total'
      - 'istio_tcp_connections_opened_total'
      - 'istio_tcp_connections_closed_total'
      - 'container_cpu_usage_seconds_total'
      - 'container_memory_working_set_bytes'
      - 'kube_deployment_spec_replicas'
      - 'kube_deployment_status_replicas'
      - 'kube_deployment_status_replicas_available' 
      endpoint: "prometheus.istio-system:9090"
      collectionInterval: 10s
      metricsPath: /federate
    enablePrometheusReceiver: true
    prometheusReceiver:
      scrapeConfigs:
        - job_name: prometheus
          static_configs:
          - targets:
            - localhost:9090
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-apiservers
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - action: keep
            regex: default;kubernetes;https
            source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_service_name
            - __meta_kubernetes_endpoint_port_name
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-nodes
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - replacement: kubernetes.default.svc:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/$1/proxy/metrics
            source_labels:
            - __meta_kubernetes_node_name
            target_label: __metrics_path__
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-nodes-cadvisor
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - replacement: kubernetes.default.svc:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
            source_labels:
            - __meta_kubernetes_node_name
            target_label: __metrics_path__
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
        - job_name: 'kube-state-metrics'
          static_configs:
            - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
        - job_name: kubernetes-service-endpoints
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_scrape
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_service_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_service_name
            target_label: service
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node
        - job_name: kubernetes-service-endpoints-slow
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_service_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_service_name
            target_label: service
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node
          scrape_interval: 5m
          scrape_timeout: 30s
        - honor_labels: true
          job_name: prometheus-pushgateway
          kubernetes_sd_configs:
          - role: service
          relabel_configs:
          - action: keep
            regex: pushgateway
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_probe
        - job_name: kubernetes-services
          kubernetes_sd_configs:
          - role: service
          metrics_path: /probe
          params:
            module:
            - http_2xx
          relabel_configs:
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_service_annotation_prometheus_io_probe
          - source_labels:
            - __address__
            target_label: __param_target
          - replacement: blackbox
            target_label: __address__
          - source_labels:
            - __param_target
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
            - __meta_kubernetes_service_name
            target_label: service
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: drop
            regex: Pending|Succeeded|Failed|Completed
            source_labels:
            - __meta_kubernetes_pod_phase
        - job_name: kubernetes-pods-slow
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: drop
            regex: Pending|Succeeded|Failed|Completed
            source_labels:
            - __meta_kubernetes_pod_phase
          scrape_interval: 5m
          scrape_timeout: 30s
    enableLoggingExporter: true
    loggingExporter:
      logLevel: info
    enablePrometheusRemoteWriteExporter: true
    prometheusRemoteWriteExporter:
      endpoint: https://metrics.cloud.aspenmesh.io/write
      externalLabels:
        cluster: aspenmesh-saas-demo-otel # Only needed to override cluster name; don't set if no override
        __replica__: otel-replica # Remove
      timeout: 30s
      headers:
        TENANT: ASPEN_SAAS_DEMO # Will be removed
        Authorization: "Basic cHJvbXNjYWxlOlFuVXlOMVZaV2paVGNWSldMMmhrZUc1aU1qRjJjbFIyY0dZeldUWXJNRWd5WXpOVGRUQXZiMUZGU1QwSw=="
        #Authorization: "Bearer API_KEY"
        X-AM-API-KEY: #whatever
      resourceConversionEnabled: true
    metrics:
      receivers: 
        - otlp
        - prometheus
      processors:
        - resourcedetection/eks
        - resourcedetection/aks
        - resourcedetection/gke
      exporters: 
        - logging
        - prometheusremotewrite
aspenmeshAgent:
  image:
    repository: ghcr.io/aspenmesh/aspenmesh-collector 
    pullPolicy: Always
    tag: "0.1.1"
  nameOverride: "amagent"
  fullnameOverride: "amagent"
  ports: 
  - containerPort: 4317
  - containerPort: 8888
  container:
    name: "aspenmesh-collector"
    args:
    - "--config=/conf/agent.yaml"
    volumeMounts:
    - name: agent-config
      mountPath: /conf
  volumes:
    - name: agent-config
      configMap:
        name: agent-config
        items:
          - key: agent.yaml
            path: agent.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
  agentConfig:
    name: "agent-config"
    enableOtlpReceiver: true
    otlpReceiver:
      protocols:
        grpc:
    enableLoggingExporter: true
    loggingExporter:
      logLevel: info
    enableOtlpExporter: true
    otlpExporter:
      endpoint: "amcollector.aspenmesh.svc.cluster.local:4317"
      insecure: true
    metrics:
      receivers: 
        - otlp
      processors: []
      exporters: 
        - logging
        - otlp
    traces:
      receivers: 
        - otlp
      processors: []
      exporters: 
        - logging
        - otlp