cert-manager:
  installCRDs: true
serviceAccount: 
  name: am-collector-sa
clusterRole:
  name: am-collector-role
  rules:
    all:
      resources:
        - nodes
        - nodes/metrics
        - services
        - endpoints
        - pods
        - configmaps
      verbs:
        - get
        - list
        - watch
    networking:
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch
    nonResourceURLs:
    - /metrics
    - /metrics/cadvisor
    nonResourceURLVerbs:
        - get
clusterRoleBinding:
  name: am-collector-role-binding
aspenmeshCollector:
  replicaCount: 1
  image:
    repository: ghcr.io/aspenmesh/aspenmesh-collector 
    pullPolicy: Always
    tag: "0.1.1"
  nameOverride: "amcollector"
  fullnameOverride: "amcollector"
  containerPort: 4317
  container:
    name: "am-collector"
    args:
    - --config=/conf/collector.yaml
    volumeMounts:
    - mountPath: /conf
      name: collector-config
  volumes:
  - name: collector-config
    configMap:
      name: collector-config
      items:
      - key: collector.yaml
        path: collector.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
  collectorConfig:
    name: "collector-config"
    enableOtlpReceiver: true
    otlpReceiver:
      protocols:
        grpc:
    enablePrometheusSimpleReceiver: true
    prometheusSimpleReceiver:
      matchParams:
      - 'istio_requests_total'
      - 'istio_request_duration_milliseconds_bucket'
      - 'istio_request_bytes_count'
      - 'istio_request_bytes_sum'
      - 'istio_response_bytes_count'
      - 'istio_response_bytes_sum'
      - 'istio_request_messages_total'
      - 'istio_response_messages_total'
      - 'istio_tcp_sent_bytes_total'
      - 'istio_tcp_received_bytes_total'
      - 'istio_tcp_connections_opened_total'
      - 'istio_tcp_connections_closed_total'
      - 'container_cpu_usage_seconds_total'
      - 'container_memory_working_set_bytes'
      - 'kube_deployment_spec_replicas'
      - 'kube_deployment_status_replicas'
      - 'kube_deployment_status_replicas_available' 
      endpoint: "prometheus.istio-system:9090"
      collectionInterval: 10s
      metricsPath: /federate
    enablePrometheusReceiver: true
    prometheusReceiver:
      scrapeConfigs:
        - job_name: prometheus
          static_configs:
          - targets:
            - prometheus.istio-system:9090
        - job_name: kube-state-metrics
          static_configs:
          - targets:
            - aspenmesh-collector-kube-state-metrics.aspenmesh.svc.cluster.local:8080
        - job_name: 'envoy-stats'
          metrics_path: /stats/prometheus
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: '.*-envoy-prom'
        - job_name: 'istiod'
          kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - istio-system
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: istiod;http-monitoring
    enableLoggingExporter: true
    loggingExporter:
      logLevel: info
    enablePrometheusRemoteWriteExporter: true
    prometheusRemoteWriteExporter:
      endpoint: https://metrics.cloud.aspenmesh.io/write
      timeout: 30s
      headers:
        Authorization: "Basic cHJvbXNjYWxlOlFuVXlOMVZaV2paVGNWSldMMmhrZUc1aU1qRjJjbFIyY0dZeldUWXJNRWd5WXpOVGRUQXZiMUZGU1QwSw=="
        X-AM-API-KEY: #whatever
      resourceConversionEnabled: true
    metrics:
      receivers: 
        - otlp
        - prometheus
      processors:
        - resourcedetection/eks
        - resourcedetection/aks
        - resourcedetection/gke
      exporters: 
        - logging
        - prometheusremotewrite
aspenmeshAgent:
  image:
    repository: ghcr.io/aspenmesh/aspenmesh-collector 
    pullPolicy: Always
    tag: "0.1.1"
  nameOverride: "amagent"
  fullnameOverride: "amagent"
  ports: 
  - containerPort: 4317
  - containerPort: 8888
  container:
    name: "aspenmesh-collector"
    args:
    - "--config=/conf/agent.yaml"
    volumeMounts:
    - name: agent-config
      mountPath: /conf
  volumes:
    - name: agent-config
      configMap:
        name: agent-config
        items:
          - key: agent.yaml
            path: agent.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
  agentConfig:
    name: "agent-config"
    enableOtlpReceiver: true
    otlpReceiver:
      protocols:
        grpc:
    enableLoggingExporter: true
    loggingExporter:
      logLevel: info
    enableOtlpExporter: true
    otlpExporter:
      endpoint: "amcollector.aspenmesh.svc.cluster.local:4317"
      insecure: true
    metrics:
      receivers: 
        - otlp
      processors: []
      exporters: 
        - logging
        - otlp
    traces:
      receivers: 
        - otlp
      processors: []
      exporters: 
        - logging
        - otlp