apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: am-collector-role-binding
  labels:
    app: {{ include "aspenmeshCollector.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: am-collector-role
subjects:
- kind: ServiceAccount
  name: am-collector-sa
  namespace: {{ .Release.Namespace }}