apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: am-collector-role
  labels:
    app: {{ include "aspenmeshCollector.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
    - nodes
    - nodes/metrics
    - services
    - endpoints
    - pods
    - configmaps
  verbs:
      - get
      - list
      - watch
- apiGroups:
  - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
    - get