---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      prometheus_simple:
        endpoint: prometheus.istio-system:9090
        collection_interval: 10s
        metrics_path: /federate
        params:
            match[]:
            - 'istio_requests_total'
            - 'istio_request_duration_milliseconds_bucket'
            - 'istio_request_bytes_count'
            - 'istio_request_bytes_sum'
            - 'istio_response_bytes_count'
            - 'istio_response_bytes_sum'
            - 'istio_request_messages_total'
            - 'istio_response_messages_total'
            - 'istio_tcp_sent_bytes_total'
            - 'istio_tcp_received_bytes_total'
            - 'istio_tcp_connections_opened_total'
            - 'istio_tcp_connections_closed_total'
            - 'container_cpu_usage_seconds_total'
            - 'container_memory_working_set_bytes'
            - 'kube_deployment_spec_replicas'
            - 'kube_deployment_status_replicas'
            - 'kube_deployment_status_replicas_available' 
      prometheus:
        config:
          scrape_configs:
            - job_name: prometheus
              static_configs:
              - targets:
                - prometheus.istio-system:9090
            - job_name: kube-state-metrics
              static_configs:
              - targets:
                - aspenmesh-collector-kube-state-metrics.{{ .Release.Namespace }}.svc.cluster.local:8080
            - job_name: 'envoy-stats'
              metrics_path: /stats/prometheus
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
            - job_name: 'istiod'
              kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                  - istio-system
              relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring
    processors:
      resourcedetection/eks:
        detectors: [env, eks]
        timeout: 2s
        override: false
      resourcedetection/aks:
        detectors: [env, aks]
        timeout: 2s
        override: false
      resourcedetection/gke:
        detectors: [env, gke]
        timeout: 2s
        override: false
    exporters:
      logging:
        loglevel: info
      prometheusremotewrite:
        endpoint: {{ .Values.promscaleEndpoint }}
        external_labels:
          cluster: {{ .Values.cluster }}
          __replica__: {{ .Values.replica }}
        timeout: 30s
        headers:
          Authorization: {{ .Values.authorization }}
          X-AM-API-KEY: {{ .Values.apiKey }}
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        metrics:
          receivers: 
            - otlp
            - prometheus
          processors:
            - resourcedetection/eks
            - resourcedetection/aks
            - resourcedetection/gke
          exporters: 
            - logging
            - prometheusremotewrite
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: {{ .Values.namespace}}
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: amcollector.{{ .Values.namespace }}.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors: []
          exporters:
            - logging
            - otlp
        metrics:
          receivers:
            - otlp
          processors: []
          exporters:
            - logging
            - otlp
