---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "aspenmeshAgent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aspenmeshAgent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aspenmeshAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aspenmeshAgent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "am.serviceAccountName" . }}
      containers:
        - name: {{ default .Chart.Name .Values.aspenmeshAgent.container.name }}
          image: "{{ .Values.aspenmeshAgent.image.repository }}:{{ .Values.aspenmeshAgent.image.tag | default .Chart.AppVersion }}"
          args:
            {{- toYaml .Values.aspenmeshAgent.container.args  | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.aspenmeshAgent.container.volumeMounts  | nindent 12 }}
          ports:
            {{- toYaml .Values.aspenmeshAgent.container.ports  | nindent 12 }}
      volumes:
        {{- toYaml .Values.aspenmeshAgent.volumes  | nindent 8 }}