apiVersion: v1
kind: Service
metadata:
  name: {{ include "aspenmeshCollector.fullname" . }}
  labels:
    {{- include "aspenmeshCollector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc-otlp
  selector:
    {{- include "aspenmeshCollector.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aspenmeshAgent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aspenmeshAgent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc-otlp
  selector:
    {{- include "aspenmeshAgent.selectorLabels" . | nindent 4 }}
